pipeline:
  publish:
    image: plugins/docker
    privileged: true
    repo: pingu/wilson
    tags: latest
    secrets: [ docker_username, docker_password ]
    when:
      status: [ success ]
      branch: [ master ]

