---
kind: pipeline
type: docker
name: pipeline
steps:
- name: publish image
  image: plugins/docker
  settings:
    repo:
      from_secret: docker_repository
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
  when:
    status: [ success ]
    branch: [ master, develop ]

- name: deploy instance
  image: quving/drone-rancher-cicd:latest
  settings:
    stamp: ${DRONE_COMMIT}
    kubernetes_deployment: telegrambot-wilson
    kubernetes_namespace: apps
    rancher_url:
      from_secret: rancher_url
    rancher_token:
      from_secret: rancher_token
    rancher_context:
      from_secret: rancher_context
  when:
    status: [ success ]
    branch: [ develop ]
